package com.canruoxingchen.uglypic.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.canruoxingchen.uglypic.dao.FootAgeType;
import com.canruoxingchen.uglypic.dao.Footage;
import com.canruoxingchen.uglypic.dao.NetSence;

import com.canruoxingchen.uglypic.dao.FootAgeTypeDao;
import com.canruoxingchen.uglypic.dao.FootageDao;
import com.canruoxingchen.uglypic.dao.NetSenceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig footAgeTypeDaoConfig;
    private final DaoConfig footageDaoConfig;
    private final DaoConfig netSenceDaoConfig;

    private final FootAgeTypeDao footAgeTypeDao;
    private final FootageDao footageDao;
    private final NetSenceDao netSenceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        footAgeTypeDaoConfig = daoConfigMap.get(FootAgeTypeDao.class).clone();
        footAgeTypeDaoConfig.initIdentityScope(type);

        footageDaoConfig = daoConfigMap.get(FootageDao.class).clone();
        footageDaoConfig.initIdentityScope(type);

        netSenceDaoConfig = daoConfigMap.get(NetSenceDao.class).clone();
        netSenceDaoConfig.initIdentityScope(type);

        footAgeTypeDao = new FootAgeTypeDao(footAgeTypeDaoConfig, this);
        footageDao = new FootageDao(footageDaoConfig, this);
        netSenceDao = new NetSenceDao(netSenceDaoConfig, this);

        registerDao(FootAgeType.class, footAgeTypeDao);
        registerDao(Footage.class, footageDao);
        registerDao(NetSence.class, netSenceDao);
    }
    
    public void clear() {
        footAgeTypeDaoConfig.getIdentityScope().clear();
        footageDaoConfig.getIdentityScope().clear();
        netSenceDaoConfig.getIdentityScope().clear();
    }

    public FootAgeTypeDao getFootAgeTypeDao() {
        return footAgeTypeDao;
    }

    public FootageDao getFootageDao() {
        return footageDao;
    }

    public NetSenceDao getNetSenceDao() {
        return netSenceDao;
    }

}
