package com.canruoxingchen.uglypic.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NET_SENCE.
 */
public class NetSence {

    private String objectId;
    private String senceNetIcon;
    private String senceParentId;
    private Integer senceOrderNum;
    private String senceName;
    private String senceDescribe;
    private String inputContent;
    private String inputRect;
    private String inputFontName;
    private Integer inputFontSize;
    private Integer inputFontColor;
    private Integer inputFontAlignment;
    private String timeRect;
    private String timeFontName;
    private Integer timeFontSize;
    private Integer timeFontColor;
    private Integer timeFontAlignment;

    public NetSence() {
    }

    public NetSence(String objectId) {
        this.objectId = objectId;
    }

    public NetSence(String objectId, String senceNetIcon, String senceParentId, Integer senceOrderNum, String senceName, String senceDescribe, String inputContent, String inputRect, String inputFontName, Integer inputFontSize, Integer inputFontColor, Integer inputFontAlignment, String timeRect, String timeFontName, Integer timeFontSize, Integer timeFontColor, Integer timeFontAlignment) {
        this.objectId = objectId;
        this.senceNetIcon = senceNetIcon;
        this.senceParentId = senceParentId;
        this.senceOrderNum = senceOrderNum;
        this.senceName = senceName;
        this.senceDescribe = senceDescribe;
        this.inputContent = inputContent;
        this.inputRect = inputRect;
        this.inputFontName = inputFontName;
        this.inputFontSize = inputFontSize;
        this.inputFontColor = inputFontColor;
        this.inputFontAlignment = inputFontAlignment;
        this.timeRect = timeRect;
        this.timeFontName = timeFontName;
        this.timeFontSize = timeFontSize;
        this.timeFontColor = timeFontColor;
        this.timeFontAlignment = timeFontAlignment;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getSenceNetIcon() {
        return senceNetIcon;
    }

    public void setSenceNetIcon(String senceNetIcon) {
        this.senceNetIcon = senceNetIcon;
    }

    public String getSenceParentId() {
        return senceParentId;
    }

    public void setSenceParentId(String senceParentId) {
        this.senceParentId = senceParentId;
    }

    public Integer getSenceOrderNum() {
        return senceOrderNum;
    }

    public void setSenceOrderNum(Integer senceOrderNum) {
        this.senceOrderNum = senceOrderNum;
    }

    public String getSenceName() {
        return senceName;
    }

    public void setSenceName(String senceName) {
        this.senceName = senceName;
    }

    public String getSenceDescribe() {
        return senceDescribe;
    }

    public void setSenceDescribe(String senceDescribe) {
        this.senceDescribe = senceDescribe;
    }

    public String getInputContent() {
        return inputContent;
    }

    public void setInputContent(String inputContent) {
        this.inputContent = inputContent;
    }

    public String getInputRect() {
        return inputRect;
    }

    public void setInputRect(String inputRect) {
        this.inputRect = inputRect;
    }

    public String getInputFontName() {
        return inputFontName;
    }

    public void setInputFontName(String inputFontName) {
        this.inputFontName = inputFontName;
    }

    public Integer getInputFontSize() {
        return inputFontSize;
    }

    public void setInputFontSize(Integer inputFontSize) {
        this.inputFontSize = inputFontSize;
    }

    public Integer getInputFontColor() {
        return inputFontColor;
    }

    public void setInputFontColor(Integer inputFontColor) {
        this.inputFontColor = inputFontColor;
    }

    public Integer getInputFontAlignment() {
        return inputFontAlignment;
    }

    public void setInputFontAlignment(Integer inputFontAlignment) {
        this.inputFontAlignment = inputFontAlignment;
    }

    public String getTimeRect() {
        return timeRect;
    }

    public void setTimeRect(String timeRect) {
        this.timeRect = timeRect;
    }

    public String getTimeFontName() {
        return timeFontName;
    }

    public void setTimeFontName(String timeFontName) {
        this.timeFontName = timeFontName;
    }

    public Integer getTimeFontSize() {
        return timeFontSize;
    }

    public void setTimeFontSize(Integer timeFontSize) {
        this.timeFontSize = timeFontSize;
    }

    public Integer getTimeFontColor() {
        return timeFontColor;
    }

    public void setTimeFontColor(Integer timeFontColor) {
        this.timeFontColor = timeFontColor;
    }

    public Integer getTimeFontAlignment() {
        return timeFontAlignment;
    }

    public void setTimeFontAlignment(Integer timeFontAlignment) {
        this.timeFontAlignment = timeFontAlignment;
    }

}
