package com.canruoxingchen.uglypic.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECENT_FOOTAGE.
 */
public class RecentFootage {

    private String objectId;
    private Long accessTime;
    private Integer footageType;
    private String json;

    public RecentFootage() {
    }

    public RecentFootage(String objectId) {
        this.objectId = objectId;
    }

    public RecentFootage(String objectId, Long accessTime, Integer footageType, String json) {
        this.objectId = objectId;
        this.accessTime = accessTime;
        this.footageType = footageType;
        this.json = json;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public Long getAccessTime() {
        return accessTime;
    }

    public void setAccessTime(Long accessTime) {
        this.accessTime = accessTime;
    }

    public Integer getFootageType() {
        return footageType;
    }

    public void setFootageType(Integer footageType) {
        this.footageType = footageType;
    }

    public String getJson() {
        return json;
    }

    public void setJson(String json) {
        this.json = json;
    }

}
